services:
  error.action_controller.parameter_missing:
    class: 'API::Errors::MissingParametersPresenter'
    scope: 'prototype'
  error.action_controller.unpermitted_parameters:
    class: 'API::Errors::UnpermittedParametersPresenter'
    scope: 'prototype'
  error.api.validation_error:
    class: 'API::Errors::ValidationErrorPresenter'
    scope: 'prototype'
  error.api.must_be_authenticated_error:
    class: 'API::Errors::MustBeAuthenticatedErrorPresenter'
    scope: 'prototype'
  error.api.must_be_anonymous_error:
    class: 'API::Errors::MustBeAnonymousErrorPresenter'
    scope: 'prototype'
  model.user:
    class: 'User'
  password.encryption:
    class: 'API::TokenGeneratorService'
  template.creation:
    class: 'API::Templates::CreationService'
  user.creation:
    class: 'API::Users::CreationService'
  user.finder:
    class: 'API::Users::FinderService'
  token.generator:
    alias: 'password.encryption'
