development:
  options:
    raise_not_found_error: false
    scope_overwrite_exception: true
  sessions:
    default:
      database: renraku-api_development
      hosts:
        - localhost:27017

test: &test
  options:
    raise_not_found_error: false
    scope_overwrite_exception: true
  sessions:
    default:
      database: renraku-api_test
      hosts:
        - localhost:27017

cucumber:
  <<: *test
